steps:
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'demo'
      - '--image'
      - 'gcr.io/$PROJECT_ID/demo:$COMMIT_SHA'
      - '--region'
      - 'asia-south2'
      - '--max-instances'
      - '10'  # Set the maximum number of instances to 100

options:
  logging: CLOUD_LOGGING_ONLY

images: [gcr.io/$PROJECT_ID/demo:$COMMIT_SHA]
